### ISSUE TITLE
Authorization should be checked against current namespace

### ISSUE THREAD

**Issue by hh-lohmann** [hafron/dtable#6]
Version 2013-12-11 checks always against the wiki's root, not (as intended) against the current page what makes it unusable in wikis with delegated rights - REASON lies in missing reference to the "$ID" variable that is used in syntax.php with "auth_quickaclcheck"! SOLUTION: add "global $ID;" at the beginning of "render()"

**Comment by israellevin** [comment]
Sent a pull request with the @hh-lohmann 's fix.
