### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by asheenlevrai** [hafron/dtable#9]
Hello :)

I noticed your dokuwiki plugin "dtable" hasn't been updated since the end of 2013. Is it still under development or did you give up with it? Anyways, it's a great plugin and thanks a lot for making it.

I wanted to add the following in the "Future Ideas" section of the documentation but I feel like my request could be totally impossible to fulfill for some reason (I know nothing about coding) and I rather post here.

In the plugin "structured data" one can enable dynamic filtering for datatable output. This means that the table that is created (parsing data from the corresponding dataentry pages) displays a 1st line of blank fields. These are actually filters that allow to display in the table only the data matching the value in the filter field. This is VERY useful since it allows finding data in large tables way faster! :)

Now, dtable is preferable in many situations and allows for more "user-friendly" editing of the data. However, I was wondering if something like dynamic filtering could be implemented into dtable?

Just let me know what you think about it.

Thank you very much in advance for your time.
Best,
-a-

**Comment by asheenlevrai** [comment]
Now I noticed there is a new version 2015-04-29 but there is no changelog associated to the new vesion

**Comment by hafron** [comment]
I've fixed that. The new version contains fix of https://github.com/hafron/dtable/issues/6. I've forgot to update change log immediately.

**Comment by asheenlevrai** [comment]
thanks a lot :)
